---
- name: Set up Paraview on Crusoe infrastructure
  hosts: all
  tasks:
    - name: Deploy Paraview 5.10.1
      ansible.builtin.unarchive:
        src: https://www.paraview.org/files/v5.10/ParaView-5.10.1-egl-MPI-Linux-Python3.9-x86_64.tar.gz
        dest: /opt
        remote_src: yes
    - name: Deploy Paraview 5.6.0
      ansible.builtin.unarchive:
        src: https://www.paraview.org/files/v5.6/ParaView-5.6.0-osmesa-MPI-Linux-64bit.tar.xz
        dest: /opt
        remote_src: yes
